### ISSUE TITLE
Void Fluid Pipe from Builcraft

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#113]
Make it craftable and test with GT Pipes

**Comment by Dream-Master** [comment]
Buildcraft pipes not conecting to Gregtech Pipes

**Comment by Dream-Master** [comment]
Correction.Need a pump from the tank and a pump on the end to using the Voidpipe

**Comment by Dream-Master** [comment]
I make Voidpipe craft able to voiding Creosote and make the Semifluid Generator early electic Age crafable.

**Comment by Namikon** [comment]
Sounds good :+1:

**Comment by Dream-Master** [comment]
New Recipe

// - Void Fluid Pipe
recipes.addShaped(<BuildCraft|Transport:item.buildcraftPipe.pipefluidsvoid>, [
[<ore:plateRubber>, <ore:craftingToolHardHammer>, <ore:plateRubber>],
[<ore:plateObsidian>, <ore:gemEnderPear>, <ore:plateObsidian>],
[<ore:plateRubber>, <ore:craftingToolWrench>, <ore:plateRubber>]]);

**Comment by Namikon** [comment]
So it's the first electrical tier? PlateObsidian is cutting saw, does it need more than 32 eu/t?

**Comment by Dream-Master** [comment]
No compressor

**Comment by Dream-Master** [comment]
readded the old recipes by blood asp

**Comment by Dream-Master** [comment]
Ender Pearl you find in Thaumcraft looting backs

**Comment by Drobac** [comment]
Voiding fluids can be done with the Thirsty Tank from AutoMagy

**Comment by Dream-Master** [comment]
Maybe let Infernal mobs not spawning in the Overworld and make the Mobs only a bot stronger

**Comment by Namikon** [comment]
If the semifluid works nicely, then it probably would be also a nice way to get some extra-power by setting up 4+ Coke Ovens. And Thirsty Tank is pretty lategame i guess, nothing for the "just arrived in steam age. yay"-player :D

**Comment by Dream-Master** [comment]
Yes set the Semifluid to early LV Age

**Comment by Drobac** [comment]
True, but is fluid voiding anything you come across before "mid-end" game, which the tank sorta fits into

**Comment by Dream-Master** [comment]
Done.
