### ISSUE TITLE
Gemblocks for Greg overwriting Thaumcraft Thaumium block

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#127]

**Comment by Dream-Master** [comment]
Thaumium Blocks from Thaumcraft not ordicted. Maybe i make a shapeless Recipe make Blocks craftable.

**Comment by Dream-Master** [comment]
Thanks to Ultra Peeks update his Gem blocks Mod to 1.4.1 solving this Problem. Thaumcraft Thauium now Ordicted.

Be available with the next Server Update
