### ISSUE TITLE
Adding Wireless Redstone Chicken Bones Edition

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#129]
Anybody against it ?

**Comment by Namikon** [comment]
I think there is a thaumcraft-redstone addon with those crystals I never used, however I'm not sure if that can be compared to WR-CBE. Anyways, it's a nice mod

**Comment by Dream-Master** [comment]
Maybe pushe that stuff to Thaumcraft research

**Comment by Namikon** [comment]
You could add the automagy crystals that are used for long distance transfer to the recipes of wr check. Haven't played with this mod yet however. Maybe drobac can decide if that's an option...?

**Comment by Drobac** [comment]
automagy wiireless has a 16 block and a line of sight limit so not nearly as powerfulll as wirelless. Ill check if there is longer range after lunch

**Comment by Drobac** [comment]
Automagy can do more then 16 blocks but then has to use Mirror magic and whatnot, in any case WR is much more practical

**Comment by Namikon** [comment]
Mod added, and pack is running
