### ISSUE TITLE
Test: BlockLimiter and AngerMod behaviour

### ISSUE THREAD

**Issue by Namikon** [Dream-Master/DreamCraft#130]
I noticed that it might be a problem that both mods execute their code server *and* clientside. It should *basically* not do any harm since all values are identical, and the server-instance (For both single and multiplayer) decides what happens in the World, but just to be sure I'd like to keep an eye on that. Maybe i'll just add server-based checks around these events.. Is the server updated yet?

Edit: According to some SMP guidelines it's fine the way I did it, but you can never be sure. Anyways: Let's observe both mods...

**Comment by Dream-Master** [comment]
OK

**Comment by Namikon** [comment]
Guess they are working, as we had no problems so far. I will close this issue, if someone finds a bug, please open a new issue
