### ISSUE TITLE
Banning plutonium from the Oregen

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#137]
Make Plutonium only available via IC2 Reactor

**Comment by Namikon** [comment]
I might have derped here. I talked to Drobac and he pointed me at something:
a) There is at least one natural nuclear reactor; Oklo (So Plutonium would/has probably form(ed) there) (https://www.youtube.com/watch?v=yS53AA_WaUk)
b) Pu244, which is the Plutonium found in GT veins, is a very very long lived Isotope (~80 Million yr hl).
The reason why it's not found in large amounts is, that Pu244 doesn't form in natural ways (except the Oklo reactor for example; It needs reactor conditions to form) and all the natual Pu244 that was created due earth's creation has decayed long ago.

So, it is perfectly fine that Pu244 spawns sporaticly around some veins

**Comment by Drobac** [comment]
SciShow to the rescue!

**Comment by Dream-Master** [comment]
So we let the mix on moon inside the game?

**Comment by Namikon** [comment]
That's what I'd suggest. It doesn't spawn that often anyways

**Comment by Drobac** [comment]
Seconded
