### ISSUE TITLE
Rogue-like dungeons treasure.

### ISSUE THREAD

**Issue by Methes** [Dream-Master/DreamCraft#14]
Hey guys,

right now in Rogue-like dungeons there's following settings:
generous=false
("Whether helpful features like brewing stands, ender chests, enchanting stations, anvils should generate.")

I think the dungeons are difficult enough that these treasures are ok.
Truth also is that these things are usually located in first few levels so it might be easy to get to them.
If you want to keep your progress as well (enchanting table after Thaumcraft) then it's pointless to allow that.
There are positives and negatives so I just wanted to bring this up. Your thoughts?

**Comment by Dream-Master** [comment]
I think the Enderchest will be gamebreaking too. I am not sure what this config changes so maybe i test it in sp first.
