### ISSUE TITLE
ZPM (Zero Point Module)

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#149]
ZPM (Zero Point Module) - recipe with mysterous crystal shards ( found on venus -needs tier IV rocket)

**Comment by Drobac** [comment]
Can an empty ZPM get charged?

**Comment by Dream-Master** [comment]
No. I asking Blood Asp to make a ZPM Battery and maybe he will make some.

**Comment by Namikon** [comment]
- do
- not
- make
- zpm
- rechargeable

It is **not** a battery, it's a enclosed subspace and you draw energy from it until it reaches maximum entropy:
http://stargate.wikia.com/wiki/Zero_Point_Module

Please call it whatever you want, but don't call a rechargeable battery ZPM.
Call it a personal favour, but please, don't.

And the recipe to build one shall the be most expensive, incredible, outer-space like thing you've ever made! The ZPM is basically the main thing in all StarGate movies/series, and they (as it would just render all episodes useless) never build one.

**Comment by Dream-Master** [comment]
I only mean a zpm tier Battery

**Comment by Dream-Master** [comment]
I will ask Blood asp for a zpm Tiered battery
