### ISSUE TITLE
shear recipes

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#150]
https://www.dropbox.com/s/bg3e7oxqmp56iav/Shears.png?dl=0

https://www.dropbox.com/s/bbyh4fqx86y70qx/Steal%20Shears.png?dl=0

**Comment by Namikon** [comment]
Looks fine

**Comment by Dream-Master** [comment]
Not added yet have to do when we made the Oregen ready

**Comment by Dream-Master** [comment]
Done.

Be in the next update.
