### ISSUE TITLE
[Suggestion] Change Iron chest recipe

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#154]
Do we need to changing Recipes not using a chest in a chest ?. (Iron chest need a wooden cheast and Iron Plates, copper chest need a wooden chest and copper plates, diasable upgrades)

**Comment by Drobac** [comment]
Only need to disable the chests in the upgrade recipes for upgrades that skip a chest tier. Just replace them with an equal amount of metal needed for the chest

**Comment by Dream-Master** [comment]
So updates removed and Chests need only a wooden chest exept the crystal Chest.

**Comment by Dream-Master** [comment]
Change lang file Silver to steel
