### ISSUE TITLE
Protection for login/dimension change

### ISSUE THREAD

**Issue by Namikon** [Dream-Master/DreamCraft#156]
A player shall be protected a time x after login or dimension change, in order to prevent death without beeing able to fight

**Comment by Drobac** [comment]
+1 like

**Comment by Namikon** [comment]
Sometimes I wonder how Minecraft can be that stable... http://pastebin.com/PPHR8563
Testworld, superflat, not touched anything. Standing perfectly still. But for the server, it looks like i'm jumping... Guess I need some kind of (large) tolerance setting for every value in order to detect player movement...

**Comment by Namikon** [comment]
Wiki: https://github.com/Dream-Master/AngerMod/wiki/The-config

**Comment by Dream-Master** [comment]
I will check it later.

**Comment by chrysator** [comment]
wouldnt it be easier to cast a invincible spell (or something similar) on
the player when he goes through a portal?

**Comment by Namikon** [comment]
Basically, that's what the mod is doing. Just with a few additional config-options to control its behaviour

**Comment by Namikon** [comment]
Bubble of protection is applied/removed as expected, so I'll consider this issue as resolved. If there are more bugs, please make a new issue
