### ISSUE TITLE
Change NASA Workbench recipe

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#157]
Following the new oregen. change the iridium in the workbench recipe to a viable material

**Comment by Dream-Master** [comment]
Done

//Nasa Workbench
recipes.addShaped(<GalacticraftCore:tile.rocketWorkbench>, [
[<gregtech:gt.metaitem.01:32652>, <gregtech:gt.metaitem.01:32740>, <gregtech:gt.metaitem.01:32652>],
[<ore:waferAdvanced>, <ore:circuitElite>, <ore:waferAdvanced>],
[<dreamcraft:item.StainlessSteelItemCasing>, <gregtech:gt.blockcasings:3>, <dreamcraft:item.StainlessSteelItemCasing>]]);

**Comment by Drobac** [comment]
Workbench cant use the Data Control Circuit as it needs platinum which isnt available at that stage

**Comment by Dream-Master** [comment]
Why its not available? I will test it

**Comment by Drobac** [comment]
Think you get platinum first on a planet, not sure which one

**Comment by Namikon** [comment]
well, platinum can be thermal-centrifuged from nickel ore. It's a pain, but it's possible

**Comment by Dream-Master** [comment]
Its only one circuit. I check how much platinum it needs

**Comment by Drobac** [comment]
Well its one platinum for a circuit, so not much

**Comment by Dream-Master** [comment]
So ok ?

**Comment by Drobac** [comment]
yep, shouldnt be a problem. Didnt check for byproducts, getting the 1 platinum just needs 5 nickle ores so not too bad
