### ISSUE TITLE
Change AFSU recipes to conform to Tungsteel tier

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#159]

**Comment by Dream-Master** [comment]
Is this the Tungstensteel Tier ?

**Comment by Drobac** [comment]
well i went with the EU tiering based on the table, but seeing as we only have GT production machines with the max of 8k it needs to be discussed

**Comment by Dream-Master** [comment]
Recipes done. In the Next update

**Comment by Dream-Master** [comment]
// --- AFSU
recipes.addShaped(<AFSU:AFSU>, [
[<ore:cableGt01Platinum>, <dreamcraft:item.TungstenSteelItemCasing>, <ore:cableGt01Platinum>],
[<dreamcraft:item.TungstenSteelItemCasing>, <gregtech:gt.blockmachines:15>, <dreamcraft:item.TungstenSteelItemCasing>],
[<dreamcraft:item.HighEnergyFlowCircuit>, <AFSU:ALC>, <dreamcraft:item.HighEnergyFlowCircuit>]]);

// --- Assembler Recipes ---

// --- AFB
Assembler.addRecipe(<AFSU:ALC>, <dreamcraft:item.HighEnergyCircuitParts>, <gregtech:gt.metaitem.01:32597>, 2400, 2048);
