### ISSUE TITLE
Add Hardcore Ender Expansion

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#16]
We make all Dimensions harder why we not making the Ender harder too. 
I think we need thid mod!?

**Comment by Methes** [comment]
I'm in!

**Comment by Dream-Master** [comment]
Drobac dont know the mod and Warlord also. I look inside this when i make the update (maybe today or wensday)

**Comment by Dream-Master** [comment]
Add in Pack 1.8. Drobac want to go to the End ;-)

**Comment by Drobac** [comment]
you make it sound like a childrens book :P

**Comment by Dream-Master** [comment]
;-)
