### ISSUE TITLE
Talisman of Nutrition

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#160]
Having a Talisman of Nutrition causes kicks with internal server error - impossible to log on

**Comment by Dream-Master** [comment]
Wich mod cause this and can you send me the error and the log that we can make a bug report.

**Comment by Drobac** [comment]
Its from thaumic horizons, just tried it in single and as soon as the talisman tries to suck up the food ( it holds food and feeds it to you when you get low on saturation) it crashes the client/kicks from the server

**Comment by Drobac** [comment]
http://pastebin.com/LDJrjuWZ
Crash report from my single player world

**Comment by Drobac** [comment]
Could use a Bukkit plugin to fix problems like this
http://dev.bukkit.org/bukkit-plugins/openinv/

**Comment by Dream-Master** [comment]
We dont have bukkit we need a forge mod.

**Comment by Namikon** [comment]
This bug is fixed in Version 1.2.3: squeek502/SpiceOfLife#6842a065c8c0df2c11a2b610158a3f08bd52ae93
Sounds like someone is going to get a refund :P

**Comment by Dream-Master** [comment]
We have version 1.2.3 and it ot works

**Comment by Dream-Master** [comment]
fixed in the next update.
