### ISSUE TITLE
Server down for maintanance 28.5.15

### ISSUE THREAD

**Issue by chrysator** [Dream-Master/DreamCraft#161]
The maintenance will take place on Thursday, 28th of May 2015 at 10:00 UTC+2.

The offtime is expected to last no longer than 30 to 60 minutes.

Chrys

**Comment by Namikon** [comment]
Am I just to stupid to convert UTC or is something wrong with Minecraft and Teamspeak?

**Comment by Dream-Master** [comment]
ts back online
