### ISSUE TITLE
SUGGESTED NEW PACK NAMES

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#162]
Dreamworld
DreamMaster's survival challenge
MC Dark Souls
New Age mining
Gregified Realism
Event Horizon
New Horizons

**Comment by Dream-Master** [comment]
VOTE VOTE VOTE !!!!!!!!!!!!!!!!
@chrysator 
@Namikon 
@Methes 
@Drobac

**Comment by Namikon** [comment]
Let's do a 3-Point voting system; Everyone selects 3 entries, where nr1 will get 3 points, nr2 2 points and nr1 1 point. That way we probably won't have a tie

Nr.1: Gregified Realism
Nr.2: New Horizons
Nr.3: none

**Comment by Dream-Master** [comment]
Nr.1: New Horizons
Nr.2: Event Horizon
Nr.3: Gregified Realism

**Comment by Drobac** [comment]
Nr.1: New Horizons
Nr.2: DROBAC WANTS WOLVERINE CLAWS!!! RAWWWRR
Nr.3: Expect to die

**Comment by Dream-Master** [comment]
Expect to die is cool too

**Comment by Dream-Master** [comment]
Nr.1: New Horizons
Nr.2: Event Horizon
Nr.3: Expect to die

**Comment by UltraPeeks** [comment]
Nr. 1: Expect to die
Nr. 2: Event Horizon
Nr. 3: Gregified Realism

**Comment by PaladinOne** [comment]
Event Horizons (I think this one sounds better plural)
New Horizons
Gregified Realism

**Comment by Namikon** [comment]
According to the placed votes so far, 1st would be "New Horizons" with 10 points. 2nd is "Event Horizons" with 7 points, followed by both "Gregified Realism" and "Expect to die" with 5 points each.
Missing votes:
@chrysator 
@Methes 
@WarlordWossman
@ausdog
@Lefty

**Comment by chrysator** [comment]
Nr 1: New Horizons
Nr 2: Gregified Realism
Nr 3: Dreamworld

**Comment by Dream-Master** [comment]
Missing votes:
@Methes
@WarlordWossman
@ausdog
@Lefty

**Comment by leftyde** [comment]
Mh New Horizons or  Dreamworld are almost on the same level, the others are more or less I dont know :I

**Comment by Dream-Master** [comment]
Missing votes:
@Methes
@WarlordWossman
@ausdog

**Comment by Methes** [comment]
Nr 1: Event Horizons (science!)
Nr 2: New Horizons (FTB like)
Nr 3: DreamWorld

**Comment by Dream-Master** [comment]
Missing votes
@WarlordWossman
@ausdog

**Comment by Teteros** [comment]
Nr.1: Gregified Realism
Nr.2: New Horizons
Nr.3: Event Horizons

**Comment by Careface1g** [comment]
Nr.1: New Horizons
Nr.2: Gregified Realism
Nr.3: New Age mining

**Comment by Dream-Master** [comment]
Missing votes
@WarlordWossman
@ausdog

**Comment by Dream-Master** [comment]
I think the New Name will be <h1>New Horizons</h1>
