### ISSUE TITLE
New Players

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#164]
We got three new Players:

jaimy14
Careface1g
Teteros

from Serbia i think.

**Comment by Teteros** [comment]
Hi all! Yeah Careface is from Serbia, Jaimy's from the Netherlands. I'm from Poland myself.
We usually hang around on our own Mumble server but will try out TS soon.
Learning the mods unfamiliar to us as we go along. Will post feedback here for sure.

Do you guys use JourneyMap, Mapwriter (Opis) or both?
Thanks for whitelisting us and the hospitality :)

**Comment by PaladinOne** [comment]
We generally use JourneyMap, and remove Opis/Mapwriter from clients as it's not necessary. JourneyMap is probably a little more resource-intensive but also looks better.

**Comment by Dream-Master** [comment]
In the next update I don't put this in the client pack.

**Comment by Namikon** [comment]
Welcome to all new players. Closing this issue as it isn't an issue (and we'll probably have a forum for such things soon)
