### ISSUE TITLE
New Thaumcraft Addon

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#165]
http://minecraft.curseforge.com/mc-mods/231061-tainted-magic-a-thaumcraft-addon

**Comment by Dream-Master** [comment]
I test it

**Comment by Drobac** [comment]
will check later when i have time, looks like it needs tainted biomes for functionalities

**Comment by Dream-Master** [comment]
no only tainted goo you can get from crucibles

**Comment by Drobac** [comment]
This mod gets many thumbs up from me. It would fill the giant gap in thaumcraft that we have between silverwood tier items and KAMI items, the costs of items are appropriate, only needs a little bit of gregifing with shadowmetal ingots (to be made with chrome/iridium tier items)

**Comment by Dream-Master** [comment]
Add to the pack in the next Update

**Comment by Namikon** [comment]
Mod added and running
