### ISSUE TITLE
Server/Pack update for 31.05.2015

### ISSUE THREAD

**Issue by Namikon** [Dream-Master/DreamCraft#169]
Important:
The Server is being updated right now as I write this, and a few important things will happen that need to be fixed in creative afterwards:

- The mod "Redlogic" is removed, and thus all LIGHTS from that mod will be gone too once the server is back up. That means: @Drobac , your base will probably be dark as hell, and mobs/infernals might spawn there. Martin might place some lights in creative later, or if you're brave enough you can do it on your own :P 
- A lot of new mods are added, such as all the ProjectRed-* stuff. These are not nerfed yet, and everyone is asked to think about a good tiering for these mods
- Due to the new ore-tiering system, all dimensions will be reset (Except the overworld). For existing portals to the nether that might have issues after that: Report them here and they shall be fixed

**Comment by Drobac** [comment]
Already replace lights a few days ago.
Also suggest replacing your portals to the TF, as when the dimensions reset the portals can put you in a bad spot or in the ground somewhere - ill gladly give you the diamonds for the portal resets.

**Comment by Namikon** [comment]
Pack running so far, with only a few minor problems
