### ISSUE TITLE
Quest "Copper" (Stone Age) hard to complete

### ISSUE THREAD

**Issue by UltraPeeks** [Dream-Master/DreamCraft#172]
Chalcopyrite spawns in large amounts, but malachite and copper ore is rather rare even in if you found the right veins. 
My suggestion would be to reduce the needed number of ores for copper and malachite to 32 or even 16 and keep chalcopyrite at 64.

**Comment by Namikon** [comment]
Changed to: 32 Chalcopyrite / 16 Copper / 16 Malachite 
Will be available in the next version
