### ISSUE TITLE
Uncraftable recipe: Beealyzer

### ISSUE THREAD

**Issue by Namikon** [Dream-Master/DreamCraft#174]
The carpenter does not accept the GregTech computer monitor in it's top slot, when the item is crafted. You can only place one in there if you spawn it in creative

**Comment by Dream-Master** [comment]
Ok I will check it.

**Comment by Dream-Master** [comment]
I think there is a gt machine for this too. Analyzing bees.

**Comment by Namikon** [comment]
There is, but you need the beealyzer to see all the specific genomes. The GT machine is only for auto-scanning and sorting

**Comment by Dream-Master** [comment]
My recipes works i test it. You need very much power for do one Beealyzer. I think about 300 000 EU.
I have to rebalance this.

**Comment by Dream-Master** [comment]
Add a Display Item in the Core Mod. Be in the next update today.
