### ISSUE TITLE
Galacticraft Addon Galaxy Space

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#18]
Nice addon for Galacticraft. I will test it today in the evening.
Added to Ties to the Rockets, Planets Mercury, Venus, and some Mars (Phobos) and Jupiter Moons (IO and Europa)

Link and Forum
http://forum.micdoodle8.com/index.php?threads/galaxy-space.4795/

**Comment by Methes** [comment]
I'm always up for more adventure options :-).

**Comment by Dream-Master** [comment]
Add in Pack 1.8 looks good. Only the Oregen i have to change maybe
