### ISSUE TITLE
Thaumcraft Shards only in Autoclave

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#183]
Disable Furnace and Blast furnace.

**Comment by Drobac** [comment]
Indeed, a much better option. Also amber in the autoclave please

**Comment by Dream-Master** [comment]
I have to fix the recipes because broken. Autoclave are ok.

**Comment by Dream-Master** [comment]
Fixed furnace Recipes and delete Blast furnace. Amber(2) you can make out of Amber Ore in the Hammer. So realy need a Autoclave recipe?

**Comment by Drobac** [comment]
not if we can do it in the hammer, guess i missed that recipe

**Comment by Dream-Master** [comment]
I add one recipes like the shard recipes

**Comment by Dream-Master** [comment]
Maybe i add on Venus some Naquada because we have only two Sources of naquadah

**Comment by Dream-Master** [comment]
With the Asteroids we have to talk with Namikon

**Comment by Dream-Master** [comment]
Ok i close this. Shards and Amber be in the Next version fixed.
