### ISSUE TITLE
Iron Backpacks

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#20]
Maybe we can change the the BackPack Mod to the Iron Backpack Mod : http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2331340-iron-backpacks

**Comment by Methes** [comment]
I'd personally like to keep the mod we have now. What I like about it is that you can equip it (and it's rendered on your character) and that you can enter it via hotkey. It has two tiers, which should be plenty.
There are many more portable storage items in the modpack also.

**Comment by Dream-Master** [comment]
Ok you can have so much bagpacks you want in the Inventory. Maybe i drop this mod.
