### ISSUE TITLE
Drop Reactor Craft Rotary Craft Electicraft

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#21]
Because Reika not let us realy nerf his stuff i want to drop this mods.

**Comment by Methes** [comment]
Agreed. He allows changing his mods if you play in Singleplayer, but if you ever want to go public with the server, it will be a problem.
I like it for the huge reactors, but I guess it creates too many issues. It might even speed up loading times if we disable it.
It will leave holes in WorldGen after his Ores, but that's not a big deal.
Be careful about this though:
"IMPORTANT NOTICE: If you remove DragonAPI from your world without first installing an FML patch (here), your modded block IDs will become scrambled and the world will be unusable!  You can remove the patch after you have loaded the world once with it installed."

**Comment by Dream-Master** [comment]
Yes i know i read this on Reikas site. I need this mod than forever or only one time ?

**Comment by Methes** [comment]
It also says "You can remove the patch after you have loaded the world once with it installed." so it should be fine just once. I've never tried it myself though. You make backups every time anyway so no worries.

**Comment by Dream-Master** [comment]
Yes i try and the world reload without problems

**Comment by Dream-Master** [comment]
Drop in Pack 1.8
