### ISSUE TITLE
Add MFFS and other Calclavia Mods

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#22]
If we drop Reikas Mods maybe we can add mffs and other Calclavia Mods to have other Techmods in the Pack.

**Comment by Methes** [comment]
I'm up for it. I even got MFFS scripts ready. It's sometimes difficult to find working build though.

Also I'm once again promoting IHL because I found out it extends GregTech chemistry, allowing you to process things more thoroughly. I'm suggesting it for the last time, I promise :D.

**Comment by Dream-Master** [comment]
I look inside that when i will make a update and asking the other Players. 
Did you see i change many things in Thaumcraft with my own Wand caps i can use my recipes.

https://github.com/Azanor/thaumcraft/issues/1539

https://github.com/Azanor/thaumcraft/issues/1532

https://github.com/jaredlll08/ModTweaker2/issues/16

https://github.com/joshiejack/ModTweaker/issues/78

**Comment by Dream-Master** [comment]
https://github.com/Azanor/thaumcraft/issues/1520

**Comment by Methes** [comment]
Yes I have and I have to say: very impressive job!

**Comment by Dream-Master** [comment]
MFFS and Resonant Induction give me a bug with fastcraft. We have to wait.
