### ISSUE TITLE
Bee Pollination Issue (Apiaries to Apiary Chests, Wood Type changes etc...)

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#24]
This Issue is fix in the next Update (Forestry)

**Comment by Dream-Master** [comment]
fixed in Update DC 1.8 today.

**Comment by Drobac** [comment]
Bug still seems to happen despite the new  version

**Comment by Dream-Master** [comment]
I see. I fix it with the next update!

**Comment by Dream-Master** [comment]
Will be fixed in 1.8.1.0 this week

**Comment by Dream-Master** [comment]
fixed
