### ISSUE TITLE
Thaumcraft Node Tracker

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#25]
Maybe we need this Mod.

http://minecraft.curseforge.com/mc-mods/227328-thaumcraft-node-tracker

**Comment by Dream-Master** [comment]
Client side only so itry to use it.

**Comment by Drobac** [comment]
Useful mod, i usually marked them using the Journey map but this is much better

**Comment by Dream-Master** [comment]
Added in 1.8
