### ISSUE TITLE
Electric Magic Tools

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#26]
After i nerfed Thaumcraft maybe we can add this mod ?

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292998-industrialcraft-2-thaumcraft-4-electro-magic

**Comment by Drobac** [comment]
Looks interesting, and nice GT/TC integration.

**Comment by Dream-Master** [comment]
I add you as Collaborator. You can edit things now.

**Comment by Dream-Master** [comment]
Maybe get when it is done
