### ISSUE TITLE
TiCo tools repairing.

### ISSUE THREAD

**Issue by Methes** [Dream-Master/DreamCraft#27]
With Moss disabled an issue is painfully visible:
There is increasing material cost for tool repairing. In previous versions there used to be a config for that but now it's missing. I already posted on the forums asking the dev, so let's see what he'll have to say for it.

**Comment by Dream-Master** [comment]
Ok maybe more uses of GT Tools and Electric GT Tools.
It is not disabled you have a chance of 5 to get this modifier. I disabled it only for additional Slots.
(Nothing is for free in our Pack ;-))

**Comment by Methes** [comment]
I didn't know that about repair.
But still - it takes a LOT of time to get your tool to max level, along with TONS of repairs. In the end it's probably not worth it to keep the tool, which seems a bit strange.

**Comment by Dream-Master** [comment]
Ok what you think we have to change (not breaking balance)?

**Comment by Methes** [comment]
We can't change anything yet because there's no config option for that.
But I thought it would be nice if we could repair our TiCo tools indefinitely - disabling repair cost scaling.
We have to wait for Iguana Tweaks devs' statement though. And you have to agree with it :).

**Comment by Dream-Master** [comment]
If you change the tool head the repair cost are lower ?

**Comment by Methes** [comment]
I haven't noticed that. Might be true, I don't know.

**Comment by Drobac** [comment]
No, every time you repair it has diminishing returns. That is every time you repair you get less durability back for the materials you invested. Perhaps we could get the moss back but put it as an infusion recipe using the TF moss, BoP moss and something extra. It would still require searching in the TF for the moss but would also require a certain ammount of TC progress to get it

**Comment by Dream-Master** [comment]
Yes i look about an Infusion Recipes

**Comment by Drobac** [comment]
How far into the Thaumcraft progression would you want to put the moss recipe, cause i have a few ideas

**Comment by Dream-Master** [comment]
After Infudion or maybe more far. Let me know your ideas.

**Comment by Drobac** [comment]
Well if you want to put it in the tier with Silverwood wands, you just need to add a primordial charm to the recipe since it requires 100 vis to make. Also you will need to change your custom recipes for the wands using silverwood cores since you put it that they require 100 vis to make and the most you have at that point is the 50 vis with your gold banded greatwood wand

**Comment by Drobac** [comment]
as for the infusion recipe i would suggest using the primordial charm as the center item, 4 TF moss around and something extra like maybe 4 earth shards using sano, terra and fabrico aspects

**Comment by Dream-Master** [comment]
You can come in TS much more easy to talk or chat

**Comment by Dream-Master** [comment]
Maybe i can change the primardial charm to 60 or 55 vis that you requiered vis discount. I am not sure if this break balance. I think it is batter get the  primardial charm to 75 need a reed wand etc.

**Comment by Dream-Master** [comment]
any new about the Mod add a config ?

**Comment by Methes** [comment]
Nope. The mod author doesn't communicate at all atm.

**Comment by Dream-Master** [comment]
so is it fixed or ignored?

**Comment by Drobac** [comment]
No answer that i know of and we put in the moss recipes anyway
