### ISSUE TITLE
What you think about this Mod ? Erebus Dimension

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#32]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287600-0-2pre10-the-erebus-dimension-of-the-arthropods-0

I try this mod in 1.6.4 and it looks very nice.

**Comment by Methes** [comment]
I personally love new adventure dimensions (like Twilight Forest) so it's a YES for me.

**Comment by Drobac** [comment]
too many bugs (arachnids) for my taste) xD

**Comment by Dream-Master** [comment]
Maybe later
