### ISSUE TITLE
Assembler recipe for pistons

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#33]
Is there a chance of getting one? since crafting those by hand is annoying and you need a ton of them for JABBA

**Comment by Dream-Master** [comment]
Yes i do some maybe tomorrow.

Ball of Moss is ready make a Infusion Recipe

**Comment by Dream-Master** [comment]
Cant do now because the Piston need too much Materials. I add later custom Blocks to an on Assembler Recipe.

**Comment by Drobac** [comment]
could so something like iron + carpenter frames ( or something else) with molten redstone

**Comment by Dream-Master** [comment]
i cant add fluids at the moment

**Comment by Dream-Master** [comment]
Maybe later
