### ISSUE TITLE
Another RWG problem.

### ISSUE THREAD

**Issue by Methes** [Dream-Master/DreamCraft#34]
Just leaving this here:
https://twitter.com/ted80_/status/562604277278203904

Maybe RWG isn't really usable atm.

**Comment by Dream-Master** [comment]
Not a real problem it means that some bop biomes are very tiny

**Comment by Dream-Master** [comment]
Yes I know the problem. But if I not have a new version I can't test anything.

**Comment by Methes** [comment]
This is not about just one version though. It is about all the versions that will come and break the map repeatedly.
Saying "maybe the future updates won't break the world" is just delaying the problem.
It is very probable (close to 100%) that there will be multiple map breaking updates, so I think that having a plan is very important.

**Comment by Dream-Master** [comment]
Ok what is your plan? 
We can move the whole Base of each Player with a Spatial Storage Cell from AE2 and transferring to a new world (128 Blocks ³) if we get big problems. We talk about future problems with consequences i not know now ? I see the problem but i not have a solution now. Let's see what future updates change. I am be sure we find a Solution for that Problem.

**Comment by Dream-Master** [comment]
Map reset with keeping Base chuncks are no problem
