### ISSUE TITLE
Galaxy space Lead ingot (6818:7)

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#42]
Smelting Gt lead dust gives Lead ingots from galaxy space which are completely unuseable. And they dont switch to gt ingots like the rest. The ingots are outside the ore dict?

**Comment by Dream-Master** [comment]
I look inside this today maybe have to ordict them.

**Comment by Dream-Master** [comment]
Its only a furnace recipes. I add it to oredict and remove the Recipes.
