### ISSUE TITLE
Coolant cell

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#48]
Making the coolant cells in the canning machine gives Universal Fluid cells filled with IC2coolant and not coolant cells so cant make other coolant cells. I suggest replacing the coolant cell in the 10k Coolant cell recipe with the unversal fluid cell

**Comment by Dream-Master** [comment]
I look inside later.

**Comment by Dream-Master** [comment]
Maybe i make recipes for both.

**Comment by Dream-Master** [comment]
Problem solved later i add a recipes for the collant cell.
