### ISSUE TITLE
Constant server crashes

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#49]
Last one at 12:26, but the server crashed 3-4 times before that

**Comment by Dream-Master** [comment]
I look later in the crash log

**Comment by Dream-Master** [comment]
Did you some special things. Crafting some new stuff or using new machines. What you are doing when the Server crash the first time?

**Comment by Drobac** [comment]
Nothing special, just going through the tunnel back to your house and grabbing the JABBA barrels with stone in them. What did the crash log say?

**Comment by Dream-Master** [comment]
Its a Forestry Bee keeping Bug

**Comment by Drobac** [comment]
same thing just happened 18:43 - Check the sleeping bag

**Comment by Dream-Master** [comment]
everythime the same error

**Comment by Drobac** [comment]
hm could bee that is why some of my princesses went missing

**Comment by Dream-Master** [comment]
ts?

**Comment by Dream-Master** [comment]
Waiting for answer from Mezz (Forestry)

**Comment by Dream-Master** [comment]
@Drobac 
Mezz need some information about the Bees:

Thanks for the report!
Should be fixed in the latest unstable.

Somehow you have an ItemStack that has a null item in the Alveary. 
Please let me know what kind of bees and products you have in the Alveary at (1424, 61, -2503).

**Comment by Drobac** [comment]
On those coords - Invincible bees, but as far as i remeber the error was also on the space station, those were frugal and refined. Could be something with extra bees

**Comment by Dream-Master** [comment]
mezz commented 31 minutes ago

Thanks!
I think it's worth reporting to Binnie's tracker, you can link back here.
There will be no more crashes from it interacting with Forestry, but I didn't do anything to remove the broken ItemStacks. it's possible that they could fill up the Alveary, or cause a crash when you pick them up or use them somehow.

**Comment by Dream-Master** [comment]
Update in 1.8.9.0

**Comment by Dream-Master** [comment]
Fixed
