### ISSUE TITLE
Can't connect to server - minetweaker error

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#50]
A fatal error has occured, connection was terminated. Console says:
"[Client thread/ERROR] [FML]: SimpleChannelHandlerWrapper exception
 java.lang.NullPointerException" 
"There was a critical exception handling a packet on channel MineTweaker3.
java.lang.NullPointerException"

**Comment by Dream-Master** [comment]
Maybe have something to do with my Thaumcraft hack scripts. You downloaded the newest pack and add all stuff like scripts configs and mods? You can start a sp game? Try to delete the scripts in your  client. I stay at work and maybe back at 7 this evening. Sorry can't check now anything.

**Comment by Dream-Master** [comment]
I connecting this night without an error

**Comment by Drobac** [comment]
Sp works fine, ill try deleting and readding the scripts

**Comment by Drobac** [comment]
i overwrote the scripts the first time, they need to be delete and added. Works fine now

**Comment by Dream-Master** [comment]
Can you looking if the Thaumcraft recipes working. I hope this error be gone. I don't want people join the server have first to reloaded the scripts

**Comment by Dream-Master** [comment]
But direct connect not possible ?

**Comment by Dream-Master** [comment]
Drobac can yo exactly described what you did. I need to know it because I don't want People reloaded scripts. Otherwise I have to back grade Mod Tweaker or find a mod that disabled  single Items.

**Comment by Drobac** [comment]
After i downloaded the pack i just copied the script folder over the old one and selected overwrite. Didnt delete the old script folder before that. To fix it, just deleted the old script folder and copied over the new

**Comment by Drobac** [comment]
Also thaumcraft recipes seem to be all right in Single player, didnt research them in Multi

**Comment by Dream-Master** [comment]
so you think the error occurs only because you don't delete the folder first. Mean if you make a new instance and copy all files inside it works well ?

**Comment by Drobac** [comment]
think it should work fine, yes
