### ISSUE TITLE
Warp theory discontinued

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#51]
Hey, I'm not going to continue working on this, since it was done as a request and it seems that the issues those people were having with TC have been fixed. If someone else wants to do anything with it, go crazy. - Mod author.

Will we get any incompatibilities if its not being updated? Or it wont be much of a problem since Thaumcraft 1.7.10 development is over as well?

**Comment by Dream-Master** [comment]
Maybe some one else continued this.  Mod. It is the only way to get permanent warp away as I know.

**Comment by Dream-Master** [comment]
I read this post already. I know you don't like the mod but I think it's a god mod for us hardcore pack. If you see some incompatible things in the future say it to me.

**Comment by Dream-Master** [comment]
Warp Theory are be continued by a new Author.

**Comment by Dream-Master** [comment]
https://github.com/arkD/WarpTheory/releases
