### ISSUE TITLE
Applied energistics problems

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#52]
Having some problems with AE items, cannot in any way get charged certus quartz crystals which means you cant get Fluix Crystals or Fluix Dust which are needed for every other part of AE. Also charged certus quartz is way too rare, There isnt a Charged ore, means you can only get it via Certus quartz ore byproducts. From an entire Certus/Barite vein i got barely 2 stacks of Charged quartz dust. Am i missing something or is this really a problem?

**Comment by Dream-Master** [comment]
You can charge Certus Quartz but i take a look now.

**Comment by Drobac** [comment]
Didnt know about that mechanic, its new since  i last played AE2. Just need to make sure that the recipe for the charger doesnt need any fluix stuff

**Comment by Drobac** [comment]
Youll have to change the recipe for the Charger, replacing the fluix crystal with something like a diamond, maybe the industrial one. Unless there is another way to get the starting fluix crystal that i dont know

**Comment by Dream-Master** [comment]
i think you not need the ae 2 charger you can make it in the electrolyzer from GT

**Comment by Drobac** [comment]
Would be nice if NEI showed anything about that

**Comment by Dream-Master** [comment]
I think it is lost since Update to Gt 5.07.07. I make a recipes for that in the electrolyzer.

**Comment by Drobac** [comment]
k good, since it doesnt work at all atm xD

**Comment by Dream-Master** [comment]
than the balance is ok ?

**Comment by Drobac** [comment]
Well since i cant make get a charged certus i cant really say :P. But the recipes looked balanced

**Comment by Dream-Master** [comment]
ok but we are not done with ae2 (Recipes)

**Comment by Drobac** [comment]
what do you still need to tweak?

**Comment by Dream-Master** [comment]
Forestry

**Comment by Dream-Master** [comment]
TS?

**Comment by Dream-Master** [comment]
I make a Electrolyzer recipes all ready but i didnt work. I look inside this today  and make aRecipes in a nother Machine. Any Ideas?

**Comment by Drobac** [comment]
Polarizer?

**Comment by Dream-Master** [comment]
Not implemented  in mine tweaker at the Moment.

**Comment by Drobac** [comment]
What GT machines are implemented in minetweaker?

**Comment by Dream-Master** [comment]
import mods.gregtech.AlloySmelter;
import mods.gregtech.Assembler;
import mods.gregtech.BlastFurnace;
import mods.gregtech.Canner;
import mods.gregtech.Centrifuge;
import mods.gregtech.CNC;
import mods.gregtech.ChemicalReactor;
import mods.gregtech.DistillationTower;
import mods.gregtech.Electrolyzer;
import mods.gregtech.ForgeHammer;
import mods.gregtech.Fuels;
import mods.gregtech.FusionReactor;
import mods.gregtech.Grinder;
import mods.gregtech.ImplosionCompressor;
import mods.gregtech.Lathe;
import mods.gregtech.PlateBender;
import mods.gregtech.PlateCutter;
import mods.gregtech.Sawmill;
import mods.gregtech.Sonictron;
import mods.gregtech.VacuumFreezer;
import mods.gregtech.Wiremill;

Electrolyzer dont work

**Comment by Drobac** [comment]
Guess the Chemical reactor is the only realistic choice then

**Comment by Dream-Master** [comment]
so one certus quartz for one charged certus Quartz Shard without Fluids (because not supported yet)

**Comment by Dream-Master** [comment]
we can input two items (maybe on restone and one certus quatz shard ?)

**Comment by Dream-Master** [comment]
ChemicalReactor.addRecipe(output, input1, input2, durationTicks);

**Comment by Drobac** [comment]
Quartz and redstone sounds good, can you do a chemical reactor recipe for the dust too? So the charged dust + sodium gets you the crystal

**Comment by Dream-Master** [comment]
better certus Quatz dust and restone is charged certus quartz dust. This dust you can make to crystals in the autoclave

**Comment by Dream-Master** [comment]
Recipes add in 1.8.9.1

**Comment by Drobac** [comment]
AE Recipes dont use oredict-ed circuits. All are using Gregtech circuits and not accepting the IC ones

**Comment by Dream-Master** [comment]
You mean the charged one? I make the Ae one craft able so for me it works. You test the Recipes? I look inside later.

**Comment by Dream-Master** [comment]
https://github.com/Dream-Master/DreamCraft/commit/dd2258dd36bce038fa595d71adbd473c6ad67288#diff-5f9e0d45782b8a36791ddc1df2be0194
i uploaded it to the server as soon as possible

**Comment by Drobac** [comment]
Think you need to do the same for Extra cells

**Comment by Dream-Master** [comment]
i change extra cells too
