### ISSUE TITLE
Not possible to join Multiplayer after Singleplayer

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#54]
Not possible to join Multiplayer after Singleplayer.

Maybe Modtweaker error.

**Comment by Dream-Master** [comment]
Cant update now because some errors. Hope Modtweaker fix that again.

**Comment by Dream-Master** [comment]
I hope it is now fixed in Pack version 2.0.0.0

**Comment by Drobac** [comment]
add the new version of DreamCraftCore in the File Browser

**Comment by Dream-Master** [comment]
I forget it?

**Comment by Dream-Master** [comment]
Be online in a few min.

**Comment by Dream-Master** [comment]
I update again i make a new pack 2.0.2.0

**Comment by Drobac** [comment]
Fixed with the new update
