### ISSUE TITLE
Disable - "Flying not enabled"

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#57]
Disable this since it just interferes with normal mod flying machines and space station navigation

**Comment by Dream-Master** [comment]
you mean the mc flying allowed on server ?

**Comment by Drobac** [comment]
yes, server sometimes randomly kicks me while going around the space station which has the specific movement system

**Comment by Dream-Master** [comment]
Allow flying on server may be cause lags. We can test it if you want

**Comment by Dream-Master** [comment]
Ok Server restart flying is allowed
