### ISSUE TITLE
LAG LAG LAG

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#58]
@Drobac your base lags 300 ms. Map unplayable.

**Comment by Dream-Master** [comment]
I think it is solved. i backgrade to Forge 1291 and delte Better Anvil(because need newer Forge)

**Comment by Drobac** [comment]
base still lagging the server or fixed?

**Comment by Dream-Master** [comment]
Downgrade to Forge 1291 fix the Problem maybe.
