### ISSUE TITLE
World Reset (Keeping Base and DIm 3) 

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#61]
Because of some missing and wrong generating Ores from GT i reset the World(Keep only the known Buildings and Dim 3)
@Methes Sorry far that i check your the Player Log on wich place you clicking Blocks and harvesting things but i can find a building. If you missing much i can give you back when i be back home.

Maybe for future World Updates /resets i need from all of you the Chuncks and Dimensions I have to keep

**Comment by Drobac** [comment]
done
