### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#62]
Extra Bees and Trees Stuff nerf
Adding Ores to Galaxy Space 1.7 (now with the newest version possible)

Adding recipes for Tier IV and Tier V rockets.
Add recipe for Ender Tank
Add recipes for Nether and End shards
Everfull Jar recipe
Fix Red Logic Lamp recipes.
Fix Vis Costs for TC staffs, add Thaumic exploration/Forbidden Magic wand cores and wand caps

**Comment by Drobac** [comment]
Add recipe for Ender Tank

**Comment by Dream-Master** [comment]
DONE Fix Bronze Ingot from IC2 to GT in TC Smeltery 
DONE Fix the other Ingots too
DONE Change Recipes Bronze Blasfurnace use Iron furnaces instead of Furnaces

**Comment by Dream-Master** [comment]
DONE Fix Boat Recipes

**Comment by Dream-Master** [comment]
Adding Ores to Galaxy Space 1.7 (now with the newest version possible)

**Comment by Dream-Master** [comment]
which ores should be on what planet. Any Suggestion. 

dimensions:

Callisto (Jupiter Moon) (Tier 3)
Europa (Jupiter Moon) (Tier 3) (Dungeon to Tier 4)
Ganymede (Jupiter Moon) (Tier 3)
IO (Jupiter Moon) (Tier 3)

Ceres(smal Planet) (Tier ?)

Deimos (Mars Moon) (Tier 2 or 3)
Phobos (Mars Moon) (Tier 2 or 3)

Mercury(Tier 5)

Venus (Tier 4) (Dungeon to Tier 5)

Titan (Saturn Moon) (Tier 5)
Enceladus (Saturn Moon) (Tier 5) (Dungeon to Tier 6 not used atm)

**Comment by Drobac** [comment]
Adding recipes for Tier IV and Tier V rockets

**Comment by Dream-Master** [comment]
Any suggestions with the orgen on the planets and moons?

**Comment by Drobac** [comment]
i suggest that all the planets after tier 3 have all the metals, even the ones we only have in twilight forest or the nether atm. Or maybe even pick a planet that could be used as a mining world with most of the metals.

Or you want the ore gens on the planets to be sorta realistic? i can check the wikis for mineral compositions

**Comment by Dream-Master** [comment]
I think all Tier 5 Planet has to have Neutronium. I tink add real orgen and mixes on the planet not make so much sense. I tink we have to add like the GT Tiersystem working.

**Comment by Dream-Master** [comment]
Will Change Deshe plates to Compresed Desh Plates on Armor and Tools

**Comment by Dream-Master** [comment]
DONE Change Desh Armor and Tools

**Comment by Dream-Master** [comment]
Better Open new TODO Issue when some things have to be done.
