### ISSUE TITLE
[Suggestion] RWG 1.3.01 Back

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#63]
I want rwg 1.3.01 back because better world generation. I test it on my Base and it works only a few blocks on the Border i have to remove not much work. What you thinking about this Idea?

**Comment by Drobac** [comment]
In what way was tje generation better? more biomes or?

**Comment by Dream-Master** [comment]
The generated terrain looks better and Nature Trees are there too. Or you find any Huge Tree and?

**Comment by Drobac** [comment]
yes natura trees are spawning

**Comment by Methes** [comment]
Better in what way? I see exactly the same terrain, maybe even better mountains. Natura trees are spawning, I've ran past one.
Also 1.3.2 has more RWG biomes, river support, proper Thaumcraft support (at least it should have Magical Forest spawning fixed).

**Comment by Dream-Master** [comment]
Ok it's only a question. If you seen natura trees on our map and magical forest biome I don't complain. Did you?

**Comment by Dream-Master** [comment]
Sorry Drobac I didn't see you post. So eucalyptus trees spawning too? Somebody see some magical forest biome or some taint? Let me know what you find and what you didn't.

**Comment by Methes** [comment]
I'm not sure about eucalyptus, I'll keep my eyes open. I did see that giant tree though.
I also haven't seen Magical forest or Taint yet. Now that I've got a horse I can do some more exploring.
However, if you're not satisfied with RWG but want interesting terrain, we can use Amplified or Biomes'o'Plenty amplified (like Etho does).

**Comment by Drobac** [comment]
Found Eucalyptus, got one near my base. Havent come across any of the thaumcraft biomes

**Comment by Dream-Master** [comment]
Maybe better waiting for Oceans update.
