### ISSUE TITLE
Boat recipe

### ISSUE THREAD

**Issue by Methes** [Dream-Master/DreamCraft#64]
Boats in MC suck. They suck even more in multiplayer.
They are extremely fragile and in multiplayer they get desynced, which makes navigating through rivers or more complicated terrain impossible.
When they break, they give you 2 planks and 2 sticks.
For that I see no reason to modify the vanilla recipe or at least not to what it is now. Several tools needed and even iron? For something that doesn't stack and breaks even on lilypads (even though it shouldn't)?
The recipe is way too expensive. Noone will use boats that way.
I'd suggest leave it vanilla or make it require 5 planks or 2 wood logs (which makes more sense) and a knife, nothing else.

**Comment by Dream-Master** [comment]
Change tomorrow

**Comment by Dream-Master** [comment]
Changed i will upload it later. Coming with the Update this evening

**Comment by Methes** [comment]
Awesome. The new recipe looks good :).
