### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#66]
Suggestions in here please.

**Comment by Methes** [comment]
Clay bucket - the recipe is pretty expensive. So far everything is balanced nicely but the bucket requires 28 clay and 2 flint mortars. That's a bit excessive.

Rotary/ReactorCraft - I've been testing it and I'm a bit torn about it now. We'd have to modify Steelleaf or Ironwood recipes to make it total Endgame. The oregen can be severely reduced but not completely disabled. And the recipes are really cheap. Would be nice to have some cool endgame power generation though.

Server Thread on Forums - I've send you a PM with proposition of how to alter it.

**Comment by Drobac** [comment]
BC tanks are imo too complicated and too expensive to craft early game.

**Comment by Methes** [comment]
Agreed on the BC tanks - they hold only 10 buckets (not really worth it Steam wise) and require pump to output. How about this?

recipes.addShaped(BCTank, [
[ClearGlass, IronRing, ClearGlass],
[ClearGlass, Wrench, ClearGlass],
[StickyResin, ClearGlass, StickyResin]]);

**Comment by Dream-Master** [comment]
@Methes 
I know the Clay Recipes is expensive but the Buckets op. You get Lava early game without hurt like Iron Buckets did. Maybe i make it a bit cheaper

**Comment by Dream-Master** [comment]
@Methes 
Steel Leave are from Twilight Forest. Why and how we have to make it endgame?

**Comment by Dream-Master** [comment]
The tanks are so expencive like the Open Block tanks before. Only need a Alloy smelter. It hold up 16 Buckets. I like to take Obsidian inside. Maybe i look for a nother recipe.

**Comment by Dream-Master** [comment]
We have to look in Reikas mods again if we can change recipes we cann add the mods maybe. Let me first see what it spawns

**Comment by Methes** [comment]
Reika lets you modify the Blast Furnace recipe using a config. Blast furnace is used to create HSLA steel, which (I believe) you need to make anything with Rotarycraft. You can make the Blast Furnace require certain predefined metals to craft it. The metals are:
ALUMITE("ingotAlumite"),
OBSIDINGOT("ingotObsidian"),
OBSIDIAN(Blocks.obsidian),
STEEL("ingotSteel"),
COPPER("ingotCopper"),
GOLD(Items.gold_ingot),
SILVER("ingotSilver"),
BRASS("ingotBrass"),
BRONZE("ingotBronze"),
TITANIUM("ingotTitanium"),
DARKSTEEL("ingotDarkSteel"),
STEELEAF(TwilightForestHandler.ItemEntry.STEELLEAF.getItem()),
IRONWOOD(TwilightForestHandler.ItemEntry.IRONWOOD.getItem()),
MANYULLYN("ingotManyullyn"),

As you can see, the only 3 items we could use for it are DarkSteel, Steeleaf and Ironwood. We have no mod adding DarkSteel so we can only use SteelLeaf or IronWood.
If you make one of those metals require top GT and Thaumcraft technology, you effectively gate whole RotaryCraft behind all GT and Thaumcraft content.

There are two problems I see right now:
1) Oregen - even setting OreDensity to 0 in the RCraft config creates some ores, although rare.
2) Price of RCraft machines - they are very cheap. Keep in mind though that if you've reached endgame GT and Thaumcraft, pretty much everything is "cheap" for you.

There might be other problems like some items might not be gated behind the Blast Furnace, so you could create them from the beginning. I don't know RCraft well enough to say that, would have to investigate.

**Comment by Dream-Master** [comment]
Why we not make the Blasfurnace uncraft able and make Recipes with Greg?

**Comment by Dream-Master** [comment]
So if Reika let us

**Comment by Dream-Master** [comment]
Tank Recipes changed. Bucket recipe changed.
