### ISSUE TITLE
Mipmaps don't work with OpenComputers

### ISSUE THREAD

**Issue by Methes** [Dream-Master/DreamCraft#70]
Was wondering for a long time why my textures are grainy.
Already reported to OpenComputers, will post any updates.

https://github.com/MightyPirates/OpenComputers/issues/1061

**Comment by Dream-Master** [comment]
have this something to do only with Open Computers ?

**Comment by Methes** [comment]
Yes. Only Open Computers do that.

**Comment by Dream-Master** [comment]
so without the mod every thing works fine ?

**Comment by Methes** [comment]
Yes. It's just mipmaps, nothing gamechanging, just graphics.

**Comment by Dream-Master** [comment]
ok.

btw i get two request from maybe new  Players. One in Gt Forum no_loki and some one in MC Forum

**Comment by Methes** [comment]
Awesooooome! :-)

**Comment by Dream-Master** [comment]
;-)

**Comment by Methes** [comment]
Fixed in 1.5.7 version (already released).

**Comment by Dream-Master** [comment]
Ok
