### ISSUE TITLE
No recipe to craft paper in early game?

### ISSUE THREAD

**Issue by Muphet** [Dream-Master/DreamCraft#73]
Dunno if that's a missing recipe, but there is no possible way of getting paper in early game (for crafting tinkers patterns) unless looted in dungeon chests. Vanilla recipe is disabled as well as presser from pam's harvest. the only way according to NEI is gregtech machines or forestry

**Comment by Dream-Master** [comment]
you can craft Paper out of Wood pulp and Water. Buckets you get back. Wood pulp you can make with the Motar.

**Comment by Dream-Master** [comment]
You can use Clay Buckets too. So it is early game but need a lot of Recources and time.

**Comment by Muphet** [comment]
oh that would make sense. now, since i can't mine copper/tin to get bronze for mortar im still stuck

**Comment by Dream-Master** [comment]
GT flint tools you can craft

**Comment by Dream-Master** [comment]
You can make a flint mortar too.

**Comment by Dream-Master** [comment]
Did it works for you? can i close this issue?

**Comment by Dream-Master** [comment]
ok works
