### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#74]
Can you reset my postion in playerdata, cannot connect to the server and its giving me an error with warded blocks in the nether.

**Comment by Dream-Master** [comment]
I can delete youd data. Than you loosing your inventory. Error with Warded Block in te Nether?

**Comment by Dream-Master** [comment]
I am 18-18.30 at home

**Comment by Drobac** [comment]
k sure. And id pref not deleting all the data, im sure there is a way to just reset the characters current position. The error happened after i warded some blocks in the nether (while making a wither skele farm), and logged off. After that i couldnt log on anymore

**Comment by Dream-Master** [comment]
i can delte the nether if this help

**Comment by Drobac** [comment]
Think it would, doubt anyone has anything significant in there

**Comment by Drobac** [comment]
Think it would, doubt anyone has anything significant in there

**Comment by Dream-Master** [comment]
Ok delete nether OK ?

**Comment by Dream-Master** [comment]
If I do this i make a small update too.

**Comment by Drobac** [comment]
sounds good on my side

**Comment by Dream-Master** [comment]
Ok

**Comment by Dream-Master** [comment]
Update done. Check if it works for you!

**Comment by Dream-Master** [comment]
OK Done
