### ISSUE TITLE
Thaumcraft Infernal mobs

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#75]
If possible id disable the Infernal mobs in the Outer lands. In the Overworld it works, but any attempt to go into the Outer lands makes it a suicide and a very big chance of losing all your items because many of the infernal special abilities can throw you into the void and your hard worked items go poof. Also i think that because of the partial magical damage the thaumcraft mobs in there do, not even quantum armor provides invulnerability. And the ammount of hard mobs in there would offset the lack of infernal mobs.

**Comment by Dream-Master** [comment]
I dont know if there are any option in the config to do this. 
Why it is so important for you to go to this Dimension?
I don't want to make all Thaumcraft mobs not infernal. 
I think you can only enable or disable Infernal effects to all mob for all Dimensions not for a specific Dimension.

**Comment by Drobac** [comment]
Well, the dimension holds the boss which drops the Primordial Pearl which is needed for all the High-end game Thaumcraft.

**Comment by Dream-Master** [comment]
ok but how i can disable effects only in one dimension?

**Comment by Dream-Master** [comment]
Cant do any thing at the moment. Have to look what we can do.

**Comment by Drobac** [comment]
Maybe just make a recipe for the primordial pearl, simplest solution

**Comment by Dream-Master** [comment]
Maybe I make a expensive recipe to double the perl mean you need only go one time to this dimension to get the first pearl. Like the loch bone. Ok for you?

**Comment by Dream-Master** [comment]
Server is offline

**Comment by Drobac** [comment]
Id have to try and get one first, ill let you know after that but i dont think itll go well

**Comment by Dream-Master** [comment]
Yes let me know if it is possible to get one. I dont want to diasable this dimension by getting things by crafting. If you get one you can double it with recipe

**Comment by Dream-Master** [comment]
Server is offline. How long is the Server offline today?

**Comment by Drobac** [comment]
dont know, havent been on toda

**Comment by Dream-Master** [comment]
Server is back online btw. Only ts not works for some reasons.

**Comment by Dream-Master** [comment]
@Drobac you check if you get one Pearl. Than i make a dublication recipes.

**Comment by Dream-Master** [comment]
Will make soon a mood that diasable Infernam Mobs in some Dimensions.
