### ISSUE TITLE
Auto chisel

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#80]
Can we get a recipe for the auto chisel and its upgrades

**Comment by Dream-Master** [comment]
In previous Version it crash the Game thats why i disabled it. And i am not sure if it losing durability or need a chisel to work becuase nothing have to be infinite.
Why you need it ? Maybe we have to check if this erro be fixed.

**Comment by Dream-Master** [comment]
btw if i make the update to day we have Fusion reactors back ;-)

**Comment by Drobac** [comment]
Fuuuusion-ha, awesome.. In single player it seemed to used up the durability. And i want it because it makes it a lot easier to get the chisel blocks for big builds

**Comment by Dream-Master** [comment]
and it not crash or mess up any thing ?

**Comment by Dream-Master** [comment]
Recipe suggestion

**Comment by Drobac** [comment]
didnt mess with anything, at least in single player. Shouldnt be too complicated, maybe something like crafting table, diamond chisel and a robotic arm

**Comment by Dream-Master** [comment]
// --- Auto Chisel
recipes.addShaped(<chisel:autoChisel>, [
[SteelScrew, <ore:ringWoodSealed>, SteelScrew],
[<gregtech:gt.metaitem.01:32630>, <gregtech:gt.metaitem.01:32744>, <gregtech:gt.metaitem.01:32650>],
[Screwdriver, <IronChest:BlockIronChest>, HHammer]]);

with roboter arm and convoyer module mv and Crafting table cover from gt

**Comment by Drobac** [comment]
looks good

**Comment by Dream-Master** [comment]
working on the upgrades and than i update the server

**Comment by Dream-Master** [comment]
Writing with Blood Asp waiting for Gt Updated Version before update the server
