### ISSUE TITLE
Nether star dust

### ISSUE THREAD

**Issue by Drobac** [Dream-Master/DreamCraft#81]
Can you make a recipe for making plates out of the dust, dust gets left over after making the lenses for the beacons

**Comment by Dream-Master** [comment]
yes sure not much work.  i am not sure if in the newest gt version 5.08.04 the duts to plates is inside allready.

**Comment by Dream-Master** [comment]
I will add a Implusion Compressor recipes for it

**Comment by Dream-Master** [comment]
4 dusts to 3 nether stars
