### ISSUE TITLE
WE NEED A NEW PACK NAME

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#82]
There are other Packs named "DreamCraft" so we have to look for a other and better Pack Name.

**Comment by Methes** [comment]
Dreamworld? :)

**Comment by Drobac** [comment]
DreamMaster's survival challenge

**Comment by Dream-Master** [comment]
;-)

**Comment by Dream-Master** [comment]
Server and TS be back on btw.

**Comment by Drobac** [comment]
MC Dark Souls?

**Comment by Dream-Master** [comment]
because it is hard right ?

**Comment by Drobac** [comment]
yep, but it needs a better name like - Evolve or die :P

**Comment by Dream-Master** [comment]
I am very bad with Names. Before we named the Pack newagemining. I registerd a de domian for that but never used. newagemining.de

**Comment by Drobac** [comment]
that works as well

**Comment by Dream-Master** [comment]
Maybe have to recativate the Domain

**Comment by Dream-Master** [comment]
btw dont see yu on the Server for a while

**Comment by Dream-Master** [comment]
@Drobac 

The Shards Problem are solved with the Gt 5.08.09 Version

**Comment by Dream-Master** [comment]
ausdog said:

I know you're looking for a new name so I was think that sense you use "gregified" a few times on your github that maybe the name of the mod pack could be something with Gregified in it, maybe something like just simply Gregified or Gregified Realism. Just an idea. Also it will be hard for me to get on much this week because I'm working on my truck and because of track practice/meets, I'll try to get on as much as I can but no promises that I'll even get on this week.

**Comment by Namikon** [comment]
Event Horizon :D

**Comment by Dream-Master** [comment]
New Horizons 
like the Name of the Nasa Name for the Pluto mission

**Comment by Namikon** [comment]
Sounds good

**Comment by Dream-Master** [comment]
So we get a lots of Suggestion we have to a decision.

I open a ne issue for this.
