### ISSUE TITLE
Infernal Mobs Blacklist in Dimension

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#89]
Infernal Mobs Blacklist in Dimension

**Comment by Namikon** [comment]
Created pull-request
https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/pull/14

**Comment by AtomicStryker** [comment]
Is pulled and everything.

**Comment by Dream-Master** [comment]
Thanks

**Comment by Dream-Master** [comment]
I downloaded the file all ready and be testing.

**Comment by Dream-Master** [comment]
Tested with Dim 0 Overworld works. Now testing with dim 1 End.

**Comment by Dream-Master** [comment]
Works fine in the end too
