### ISSUE TITLE
Make a mod that give Damage on some Items (Lava Buckets etc)

### ISSUE THREAD

**Issue by Dream-Master** [Dream-Master/DreamCraft#99]
Make a mod that give Damage on some Items (Lva Buckets etc)

**Comment by Namikon** [comment]
CoreMod 0.4.6 has a first draft of that, but I recommend to not use it (yet) as it isn't finished and could probably crash the server in some .. nasty ways...

**Comment by Namikon** [comment]
Update: Current commit of 0.4.6 has another few fixes for the "HazardousItems" module and is ready to be tested in a local, isolated, nuke-proof environment. A few tings:
The module can be (almost) entirely configured *ingame*. Type /hazardousitems help (or /hazit help) to get the ingame documentation.

The config file can also be reloaded while the server is running, and it will notify you if it was successful or not. If it's not, nothing will explode, as the old settings are kept in memory until a new valid configuration is found. The module is not yet working with fluid containers, as this requires some more investigation about how mods interact with the Forge Fluid-Registry, but this is a good time to hunt for bugs.

The module is self-monitoring its performance, as the PlayerTick event may cause serious lag if a) a lot of players are online and b) they have a lot of stuff in their inventories. It will increase the time it waits between inventory checks and thus (probably...) lower the tps impact.

**Comment by Dream-Master** [comment]
Testing when i come back home. 7 o Clock. You be in the TS?

**Comment by Namikon** [comment]
Yep, will be there

**Comment by Namikon** [comment]
Dream-Master/DreamCraft-CoreMod@fcf1600a3e112452e9140e37c990b7dde808aa91 should fix the problem you had yesterday. Can't test it here because reasons

**Comment by Dream-Master** [comment]
I test it when I be back home

**Comment by Dream-Master** [comment]
Tested and it woks.
Need only Fluid Container add.

**Comment by Namikon** [comment]
Today's update adds fluid container support.
See the wiki page for details:
https://github.com/Dream-Master/DreamCraft-CoreMod/wiki/Config-Files:-HazardousItems.xml

**Comment by Namikon** [comment]
Closed as everything is added and working as expected
